export const CHAR_DB = {
  KIM: {
    name: '김민채',
    emoji: '🐽',
    color: '#ff3344',
    altColor: '#ff7675',
    hp: 250,
    speed: 1.5,
    coolSpeed: 0.37,
    maxUltCharge: 3,
    stats: { atk: 68, def: 86, spd: 50, cool: 85, ult: 74, utl: 69 },
    desc: 'BL지식을 바탕으로 상대를 매료시키고 강력한 흡입력으로 집어삼킵니다.',
    basic: { name: 'BL을 보라고!', damage: 15, type: 'BL_THROW' },
    ult: { name: '170KG급 먹방', damage: 45, type: 'EAT_ALL' }
  },
  GONG: {
    name: '공병은',
    emoji: '🗣️',
    color: '#00e676',
    altColor: '#55efc4',
    hp: 250,
    speed: 1.625,
    coolSpeed: 0.44,
    maxUltCharge: 3,
    stats: { atk: 75, def: 43, spd: 95, cool: 68, ult: 88, utl: 71 },
    desc: '끊임없는 불평과 돌진으로 적을 교란하고 소파를 떨어뜨립니다.',
    basic: { name: '난 불만하지', damage: 20, type: 'DASH_COMPLAINT' },
    ult: { name: '버츄얼 인세니티', damage: 40, type: 'SOFA_DROP' }
  },
  PARK: {
    name: '박지성',
    emoji: '👁️',
    color: '#00d2d3',
    altColor: '#00cec9',
    hp: 250,
    speed: 1.375,
    coolSpeed: 0.30,
    maxUltCharge: 2,
    stats: { atk: 95, def: 41, spd: 79, cool: 39, ult: 94, utl: 66 },
    desc: '조준 사격으로 적을 저격하고 궁극기로 레이저 빔을 발사합니다.',
    basic: { name: '저격왕', damage: 23, type: 'SNIPER_BULLET' },
    ult: { name: 'I SEE YOU', damage: 0, type: 'EYE_LASER' }
  },
  TV: {
    name: '김티비',
    emoji: '📺',
    color: '#ff9f43',
    altColor: '#ffeaa7',
    hp: 250,
    speed: 1.5625,
    coolSpeed: 0.40,
    maxUltCharge: 3,
    stats: { atk: 68, def: 53, spd: 59, cool: 73, ult: 86, utl: 100 },
    desc: '똥 트랩을 설치하고 퍼리 버스트로 난사 공격을 퍼붓습니다.',
    basic: { name: '똥먹방', damage: 20, type: 'POOP_THROW' },
    ult: { name: 'SSR급 퍼리 니케샷', damage: 40, type: 'FURRY_BURST' }
  },
  GAEUN: {
    name: '김가은',
    emoji: '🎨',
    color: '#e84393',
    altColor: '#fd79a8',
    hp: 250,
    speed: 1.5,
    coolSpeed: 0.37,
    maxUltCharge: 3,
    stats: { atk: 57, def: 60, spd: 74, cool: 81, ult: 74, utl: 67 },
    desc: '선 가르기 공간 절단과 웹툰 스크롤 영역으로 적을 압박합니다.',
    basic: { name: '스케치', damage: 15, type: 'CUT_DIVIDE' },
    ult: { name: 'ㄹㅈㄷ 정주행', damage: 45, type: 'WEBTOON_SCROLL' }
  },
  GEONWOO: {
    name: '김건우',
    emoji: '🎧',
    color: '#8c7ae6',
    altColor: '#a29bfe',
    hp: 250,
    speed: 1.5625,
    coolSpeed: 0.44,
    maxUltCharge: 2,
    stats: { atk: 67, def: 60, spd: 72, cool: 89, ult: 76, utl: 87 },
    desc: '저음 서브우퍼 충격파로 적을 튕겨내고 전술 암전 구역을 생성합니다.',
    basic: { name: '저음 보이스', damage: 18, type: 'SUBWOOFER' },
    ult: { name: '전술 연막 활성화', damage: 40, type: 'NIGHTFALL_ZONE' }
  },
  CRIMINAL: {
    name: '흉악범',
    emoji: '🌹',
    color: '#c23616',
    altColor: '#e84118',
    hp: 250,
    speed: 1.5,
    coolSpeed: 0.42,
    maxUltCharge: 3,
    stats: { atk: 49, def: 53, spd: 72, cool: 100, ult: 71, utl: 93 },
    desc: '단검 2연투척으로 쿨타임을 강탈하고, 반격 자세 후 허수아비 폭탄을 남깁니다.',
    basic: { name: '단검 던지기', damage: 7, type: 'PICKPOCKET_DAGGER' },
    ult: { name: '흉악범의 피날레', damage: 35, type: 'FAKE_ESCAPE' }
  },
  KUJO: {
    name: '쿠죠 박타로',
    emoji: '🧢',
    color: '#341f97',
    altColor: '#f1c40f',
    hp: 250,
    speed: 1.5,
    coolSpeed: 0,
    maxUltCharge: 12,
    stats: { atk: 75, def: 51, spd: 79, cool: 100, ult: 100, utl: 86 },
    desc: '상시 발동 오라오라 구역(2.8배 확장, 2뎀/0.15초)으로 적을 타격하며, 12타 적중 시 4초간 시간을 멈추고 스탠드 화살(30뎀)을 던집니다.',
    basic: { name: '오라오라 러쉬', damage: 2, type: 'ORA_AURA' },
    ult: { name: '스타 박래티나: 더 월드', damage: 30, type: 'TIME_STOP_WORLD' }
  },
  GAMBLER: {
    name: '도박꾼 공병은',
    emoji: '🎲',
    color: '#f1c40f',
    altColor: '#00cec9',
    hp: 250,
    speed: 1.55,
    coolSpeed: 0.40,
    maxUltCharge: 3,
    stats: { atk: 92, def: 38, spd: 82, cool: 76, ult: 98, utl: 95 },
    desc: '운에 모든 것을 건 인생역전 도박꾼! 고정된 주사위 수치와 🎰 777 잭팟 연출로 전황을 뒤엎습니다.',
    basic: { name: '주사위 던지기', damage: 0, type: 'DICE_ROLL' },
    ult: { name: '올인 잭팟 777', damage: 77, type: 'ALL_IN_JACKPOT' }
  },
  KIM_AWAKENED: {
    name: '김민채(각성)',
    emoji: '🌋',
    color: '#e84118',
    altColor: '#ff7675',
    hp: 250,
    speed: 1.5,
    coolSpeed: 0.38,
    maxUltCharge: 3,
    stats: { atk: 88, def: 85, spd: 65, cool: 75, ult: 90, utl: 78 },
    desc: '강력한 170kg 지진 찍기와 5초간 마그마 길을 남기며 폭주하는 메가 마그마 볼링 스페셜리스트',
    basic: { name: '170kg 지진 찍기', damage: 18, type: 'EARTHQUAKE_SLAM' },
    ult: { name: '메가 마그마 볼링', damage: 16, type: 'MEGA_BOWLING' }
  }
};
